# Generated by Django 3.2.12 on 2022-02-24 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatBotManager',
        ),
    ]
