# Generated by Django 3.2.12 on 2022-02-24 16:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairMessage',
            fields=[
                ('id', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pairs.pair')),
            ],
        ),
    ]
