# Generated by Django 3.2.12 on 2022-02-24 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pair',
            name='value',
        ),
    ]
